-- 회원
DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER (
   USER_ID   VARCHAR2(50),
   USER_PWD   VARCHAR2(100) NOT NULL,
   USER_NAME   VARCHAR2(30) NOT NULL,
   BIRTHDAY   VARCHAR2(30) NOT NULL,
   PHONE   VARCHAR2(30) NOT NULL,
   FACEBOOK_ID   CHAR(1) ,
   HOST_CHECK   CHAR(1) ,
   ADMIN_CHECK   CHAR(1) ,
    CONSTRAINT PK_UID PRIMARY KEY (USER_ID)
);
COMMENT ON COLUMN MEMBER.USER_ID IS '아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.USER_NAME IS '이름';
COMMENT ON COLUMN MEMBER.BIRTHDAY IS '생년월일';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.FACEBOOK_ID IS '페이스북 체크';
COMMENT ON COLUMN MEMBER.HOST_CHECK IS '사장님 체크';
COMMENT ON COLUMN MEMBER.ADMIN_CHECK IS '관리자 체크';

--계좌
DROP TABLE ACCOUNT CASCADE CONSTRAINTS;
CREATE TABLE ACCOUNT (
   ACCOUNT_NUM VARCHAR2(50) NOT NULL,
   BANK_NAME VARCHAR(50) NOT NULL,
   ROOM_NO NUMBER NOT NULL,
       CONSTRAINT PK_ACC_NO PRIMARY KEY (ACCOUNT_NUM)
);
COMMENT ON COLUMN ACCOUNT.ACCOUNT_NUM  IS '계좌번호';
COMMENT ON COLUMN ACCOUNT.BANK_NAME  IS '은행이름';
COMMENT ON COLUMN ACCOUNT.ROOM_NO  IS '숙소 번호';

-- 메세지
DROP TABLE MESSAGE CASCADE CONSTRAINTS;
CREATE TABLE MESSAGE (
   MESSAGE_NO   NUMBER,
   USER_ONE   VARCHAR2(50) NOT NULL,
    USER_TWO    VARCHAR2(50) NOT NULL,          
    CONSTRAINT PK_MESG_NO PRIMARY KEY (MESSAGE_NO)
);
COMMENT ON COLUMN MESSAGE.MESSAGE_NO is '메세지 번호';
COMMENT ON COLUMN MESSAGE.USER_ONE is '사용자1';
COMMENT ON COLUMN MESSAGE.USER_TWO is '사용자2';


--메세지 디테일
DROP TABLE MESSAGE_DETAIL CASCADE CONSTRAINTS;
CREATE TABLE MESSAGE_DETAIL (
    MESSAGE_NO   NUMBER,
    MESSAGE_DATE DATE DEFAULT SYSDATE,
    CONTENT   VARCHAR2(100),
    WRITER VARCHAR2(50)
);
COMMENT ON COLUMN MESSAGE_DETAIL.MESSAGE_NO is '메세지 번호';
COMMENT ON COLUMN MESSAGE_DETAIL.MESSAGE_DATE is '메세지 작성날짜';
COMMENT ON COLUMN MESSAGE_DETAIL.CONTENT is '내용';
COMMENT ON COLUMN MESSAGE_DETAIL.WRITER is '글쓴이';


-- 내가 저장한 숙소
DROP TABLE MY_ROOM CASCADE CONSTRAINTS;
CREATE TABLE MY_ROOM (
   USER_ID   VARCHAR2(20),
   ROOM_NO   NUMBER,
    CONSTRAINT PK_UID_RNO PRIMARY KEY (USER_ID, ROOM_NO)
);
COMMENT ON COLUMN MY_ROOM.USER_ID is '아이디';
COMMENT ON COLUMN MY_ROOM.ROOM_NO is '숙소 번호';


-- 내가 가지고 있는 쿠폰
DROP TABLE MY_COUPON CASCADE CONSTRAINTS;
CREATE TABLE MY_COUPON (
   COUPON_NO   NUMBER,
   USER_ID   VARCHAR2(50),
    CONSTRAINT PK_CNO_UID PRIMARY KEY (COUPON_NO, USER_ID)
);
COMMENT ON COLUMN MY_COUPON.COUPON_NO is '쿠폰 번호';
COMMENT ON COLUMN MY_COUPON.USER_ID is '아이디';

-- 관광지
DROP TABLE TOUR CASCADE CONSTRAINTS;

CREATE TABLE TOUR (
   TOUR_NO   NUMBER,
   TOUR_CATEGORY_NO      NUMBER NOT NULL,
   TOUR_NAME   VARCHAR2(200) NOT NULL,
   TOUR_ACT_START_DATE    VARCHAR2(50),
   TOUR_ACT_END_DATE VARCHAR2(50),
   TOUR_CONTENT  LONG NOT NULL,
   TOUR_ROADADDRESS VARCHAR2(200),
   TOUR_MOREINFO VARCHAR2 ( 2000),
   TOUR_THUM_IMAGE VARCHAR2 (2000),
   TOUR_READCOUNT          NUMBER DEFAULT 0,
   USER_ID   VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_TNO PRIMARY KEY (TOUR_NO)
);

COMMENT ON COLUMN TOUR.TOUR_NO IS '관광지 게시글 번호';
COMMENT ON COLUMN TOUR.TOUR_CATEGORY_NO IS '카테고리 번호';
COMMENT ON COLUMN TOUR.TOUR_NAME IS '관광지 게시글 제목';
COMMENT ON COLUMN TOUR.TOUR_ACT_START_DATE IS '관광지 체험 시작 날짜';
COMMENT ON COLUMN TOUR.TOUR_ACT_END_DATE IS '관광지 체험 마지막 날짜';
COMMENT ON COLUMN TOUR.TOUR_CONTENT IS '관광지 게시글 내용';
COMMENT ON COLUMN TOUR.TOUR_ROADADDRESS IS '관광지 주소';
COMMENT ON COLUMN TOUR.TOUR_MOREINFO IS '알아두어야 할 사항';
COMMENT ON COLUMN TOUR.TOUR_THUM_IMAGE IS '관광지 썸네일 사진';
COMMENT ON COLUMN TOUR.TOUR_READCOUNT IS '관광지 조회 수';
COMMENT ON COLUMN TOUR.USER_ID IS '이메일 아이디';


-- 관광지 카테고리
DROP TABLE TOUR_CATEGORY CASCADE CONSTRAINTS;
CREATE TABLE TOUR_CATEGORY (
   TOUR_CATEGORY_NO NUMBER,
   TOUR_CATEGORY_NAME   VARCHAR2(50) NOT NULL,
      CONSTRAINT PK_TCNO PRIMARY KEY (TOUR_CATEGORY_NO)
);

COMMENT ON COLUMN TOUR_CATEGORY.TOUR_CATEGORY_NO IS '카테고리 번호';
COMMENT ON COLUMN TOUR_CATEGORY.TOUR_CATEGORY_NAME IS '카테고리 이름';


-- 관광지 사진
DROP TABLE TOUR_IMAGE CASCADE CONSTRAINTS;
CREATE TABLE TOUR_IMAGE(
   TOUR_IMAGE_NO   NUMBER,
   TOUR_ORIGINAL_FILE    VARCHAR2(50),
   TOUR_RENAME_FILE     VARCHAR2(50),
   TOUR_NO           NUMBER  NOT NULL,
      CONSTRAINT PK_TIMANO PRIMARY KEY (TOUR_IMAGE_NO)
);

COMMENT ON COLUMN TOUR_IMAGE.TOUR_IMAGE_NO IS '관광지 사진 번호';
COMMENT ON COLUMN TOUR_IMAGE.TOUR_ORIGINAL_FILE IS '관광지 처음 이미지';
COMMENT ON COLUMN TOUR_IMAGE.TOUR_RENAME_FILE IS '관광지 바뀐 이미지';
COMMENT ON COLUMN TOUR_IMAGE.TOUR_NO IS '관광지 게시글 번호';

-- 관광지 좋아요
DROP TABLE TOUR_LIKE CASCADE CONSTRAINTS;
CREATE TABLE TOUR_LIKE(
   TOUR_NO NUMBER NOT NULL,
   USER_ID VARCHAR2(50) NOT NULL,
   COUNT  NUMBER DEFAULT 0,
     CONSTRAINT PK_TLIKE PRIMARY KEY (TOUR_NO, USER_ID)
);

COMMENT ON COLUMN TOUR_LIKE.TOUR_NO IS '관광지 게시글 번호';
COMMENT ON COLUMN TOUR_LIKE.USER_ID IS '이메일 아이디';
COMMENT ON COLUMN TOUR_LIKE.COUNT IS '좋아요 카운터';

-- 관광지 리뷰
DROP TABLE TOUR_REVIEW CASCADE CONSTRAINTS;
CREATE TABLE TOUR_REVIEW(
   TOUR_REVIEW_NO NUMBER NOT NULL,
   TOUR_REVIEW_CONTENT  VARCHAR2(1000),
    TOUR_REVIEW_DATE DATE DEFAULT SYSDATE,
   TOUR_SCORE  NUMBER,
   TOUR_NO  NUMBER  NOT NULL,
   USER_ID  VARCHAR2(50)  NOT NULL,
      CONSTRAINT PK_TRENO PRIMARY KEY (TOUR_REVIEW_NO)
);
COMMENT ON COLUMN TOUR_REVIEW.TOUR_REVIEW_NO IS '리뷰 글 번호';
COMMENT ON COLUMN TOUR_REVIEW.TOUR_REVIEW_CONTENT IS '리뷰 내용';
COMMENT ON COLUMN TOUR_REVIEW.TOUR_REVIEW_DATE IS '리뷰 작성 날짜';
COMMENT ON COLUMN TOUR_REVIEW.TOUR_SCORE IS '평점';
COMMENT ON COLUMN TOUR_REVIEW.TOUR_NO IS '관광지 게시글 번호';
COMMENT ON COLUMN TOUR_REVIEW.USER_ID IS '이메일 아이디';


-- 자주 묻는 질문
DROP TABLE FAQ CASCADE CONSTRAINTS;
CREATE TABLE FAQ (
   FAQ_NO   NUMBER NOT NULL,
   FAQ_TITLE   VARCHAR2(50)NOT NULL,
   FAQ_RCONTENT   VARCHAR2(2000) NOT NULL,
   FAQ_READCOUNT NUMBER,
   FAQCATEGORY_NO   NUMBER NOT NULL,
    CONSTRAINT PK_FNO PRIMARY KEY (FAQ_NO)
);

COMMENT ON COLUMN FAQ.FAQ_NO IS '자주 묻는 질문 번호';
COMMENT ON COLUMN FAQ.FAQ_TITLE IS '자주 묻는 질문 제목';
COMMENT ON COLUMN FAQ.FAQ_RCONTENT IS '자주 묻는 질문 답변';
COMMENT ON COLUMN FAQ.FAQ_READCOUNT IS '자주 묻는 질문 조회수';
COMMENT ON COLUMN FAQ.FAQCATEGORY_NO IS '자주 묻는 질문 카테고리 번호';

--자주 묻는 질문 카테고리
DROP TABLE FAQ_TYPE CASCADE CONSTRAINTS;
CREATE TABLE FAQ_TYPE(
   FAQCATEGORY_NO NUMBER,
   FAQCATEGORY_NAME   VARCHAR2(30),
      CONSTRAINT PK_FTNO PRIMARY KEY (FAQCATEGORY_NO)
);

COMMENT ON COLUMN FAQ_TYPE.FAQCATEGORY_NO IS '자주 묻는 질문 카테고리 번호';
COMMENT ON COLUMN FAQ_TYPE.FAQCATEGORY_NAME IS '자주 묻는 질문 카테고리 이름';


-- 편의 시설
DROP TABLE AMENITY CASCADE CONSTRAINTS;
CREATE TABLE AMENITY (
    AMENITY_NO NUMBER ,
   AMENITY_NAME   VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_AM_NO PRIMARY KEY (AMENITY_NO)
);
COMMENT ON COLUMN AMENITY.AMENITY_NAME IS '편의시설 이름';
COMMENT ON COLUMN AMENITY.AMENITY_NO IS '편의시설 번호';


-- 시설
DROP TABLE FACILITY CASCADE CONSTRAINTS;
CREATE TABLE FACILITY (
    FACILITY_NO NUMBER,
   FACILITY_NAME   VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_FA_NO PRIMARY KEY (FACILITY_NO)
);
COMMENT ON COLUMN FACILITY.FACILITY_NAME IS '시설 이름';
COMMENT ON COLUMN FACILITY.FACILITY_NO IS '시설 번호';

-- 건물 유형
DROP TABLE BUILD_TYPE CASCADE CONSTRAINTS;
CREATE TABLE BUILD_TYPE (
    BU_TYPE_NO NUMBER,
   BU_TYPE_NAME   VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_BUTYPE_NO PRIMARY KEY (BU_TYPE_NO)
);
COMMENT ON COLUMN BUILD_TYPE.BU_TYPE_NAME IS '건물 유형 이름';
COMMENT ON COLUMN BUILD_TYPE.BU_TYPE_NO IS '건물 유형 번호';


-- 이용 규칙
DROP TABLE RULE CASCADE CONSTRAINTS;
CREATE TABLE RULE (
    RULE_NO NUMBER,
   RULE_NAME   VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_RU_NO PRIMARY KEY (RULE_NO)
);
COMMENT ON COLUMN RULE.RULE_NAME IS '이용규칙';
COMMENT ON COLUMN RULE.RULE_NO IS '이용규칙 번호';

--이벤트
DROP TABLE EVENT CASCADE CONSTRAINTS;
CREATE TABLE EVENT (
   EVENT_NO   NUMBER   NOT NULL,
   EVENT_NAME   VARCHAR2(50)   NOT NULL,
   EVENT_CONTENT   VARCHAR2(2000)   NOT NULL,
   EVENT_FIMG   VARCHAR2(50)   NOT NULL,
   EVENT_RIMG   VARCHAR2(50)   NOT NULL,
   COUPON_NO   NUMBER   NOT NULL,
   SUM_FIMG   VARCHAR2(50)   NOT NULL,
   SUM_RIMG   VARCHAR2(50)   NOT NULL,
    CONSTRAINT PK_EVNO PRIMARY KEY (EVENT_NO)   
);

COMMENT ON COLUMN EVENT.EVENT_NO IS '이벤트 번호';
COMMENT ON COLUMN EVENT.EVENT_NAME IS '이벤트 이름';
COMMENT ON COLUMN EVENT.EVENT_CONTENT IS '이벤트 내용';
COMMENT ON COLUMN EVENT.EVENT_FIMG IS '이벤트 처음 이미지이름';
COMMENT ON COLUMN EVENT.EVENT_RIMG IS '이벤트 바뀐이름 이미지이름';
COMMENT ON COLUMN EVENT.COUPON_NO IS '쿠폰번호';
COMMENT ON COLUMN EVENT.SUM_FIMG IS '썸네일 이미지';
COMMENT ON COLUMN EVENT.SUM_RIMG IS '썸네일 바뀐 이미지';

-- 쿠폰
DROP TABLE COUPON CASCADE CONSTRAINTS;
CREATE TABLE COUPON (
   COUPON_NO   NUMBER   NOT NULL,
   COUPON_MONEY   NUMBER   NOT NULL,
   COUPON_BEGIN   DATE   NOT NULL,
   COUPON_END   DATE   NOT NULL,
  CONSTRAINT PK_CNO PRIMARY KEY (COUPON_NO)   
);

COMMENT ON COLUMN COUPON.COUPON_NO IS '쿠폰 번호';
COMMENT ON COLUMN COUPON.COUPON_MONEY IS '쿠폰 금액';
COMMENT ON COLUMN COUPON.COUPON_BEGIN IS '쿠폰 시작 날짜';
COMMENT ON COLUMN COUPON.COUPON_END IS '쿠폰 끝나는 날짜';


--1:1문의
DROP TABLE QUESTION CASCADE CONSTRAINTS;
CREATE TABLE QUESTION (
   QUESTION_NO   NUMBER   NOT NULL,
   QUESTION_TITLE VARCHAR2(50) NOT NULL,
   QUESTION_CONTENT   VARCHAR2(2000),
   QUESTION_RCONTENT   VARCHAR2(2000),
   QUESTION_FIMG   VARCHAR2(50),
   QUESTION_RIMG   VARCHAR2(50),
   QUESTION_SENDEMAIL CHAR(1) DEFAULT 'N' CHECK(QUESTION_SENDEMAIL IN('Y','N')),
   USER_ID   VARCHAR2(50),
   QUESTIONTYPE_NO    NUMBER   NOT NULL,
   CONSTRAINT PK_QNO PRIMARY KEY (QUESTION_NO)
);

COMMENT ON COLUMN QUESTION.QUESTION_NO IS '1:1 문의 번호';
COMMENT ON COLUMN QUESTION.QUESTION_TITLE IS '1:1 문의 제목';
COMMENT ON COLUMN QUESTION.QUESTION_CONTENT IS '1:1 문의 내용';
COMMENT ON COLUMN QUESTION.QUESTION_RCONTENT IS '1:1 문의 답변';
COMMENT ON COLUMN QUESTION.QUESTION_FIMG IS '1:1 문의 처음 이미지';
COMMENT ON COLUMN QUESTION.QUESTION_RIMG IS '1:1 문의 바뀐 이미지';
COMMENT ON COLUMN QUESTION.QUESTION_SENDEMAIL IS '1:1문의 이메일보내기';
COMMENT ON COLUMN QUESTION.USER_ID IS '이메일 아이디';
COMMENT ON COLUMN QUESTION.QUESTIONTYPE_NO IS '1:1 문의 유형 번호';

--1:1 문의 유형
DROP TABLE QUESTION_TYPE CASCADE CONSTRAINTS;
CREATE TABLE QUESTION_TYPE (
   QUESTIONTYPE_NO     NUMBER NOT NULL,
   QUESTIONTYPE_NAME   VARCHAR2(30)   NOT NULL,
   CONSTRAINT PK_QTNO PRIMARY KEY (QUESTIONTYPE_NO)
);

COMMENT ON COLUMN QUESTION_TYPE.QUESTIONTYPE_NO IS '1:1문의 유형 번호';
COMMENT ON COLUMN QUESTION_TYPE.QUESTIONTYPE_NAME IS '1:1문의 유형 이름';

---약관 및 정책
DROP TABLE POLICY CASCADE CONSTRAINTS;
CREATE TABLE POLICY (
   POLICY_NO   NUMBER   NOT NULL,
   POLICY_TYPE   VARCHAR2(30)   NOT NULL,
   POLICY_TITLE   VARCHAR2(30)   NOT NULL,
   POLICY_CONTENT   VARCHAR2(2000)   NOT NULL,
  CONSTRAINT PK_PNO PRIMARY KEY (POLICY_NO)
);

COMMENT ON COLUMN POLICY.POLICY_NO IS '약관 및 정책 번호';
COMMENT ON COLUMN POLICY.POLICY_TYPE IS '약관 및 정책 유형';
COMMENT ON COLUMN POLICY.POLICY_TITLE IS '약관 및 정책 제목';
COMMENT ON COLUMN POLICY.POLICY_CONTENT IS '약관 및 정책 내용';


--예약 내용
DROP TABLE RESERVATION CASCADE CONSTRAINTS;
CREATE TABLE RESERVATION (
   ROOM_NO NUMBER,
   A_NUM NUMBER NOT NULL,
   C_NUM NUMBER,
   I_NUM NUMBER,
   CHECKIN_DATE DATE NOT NULL,
   CHECKOUT_DATE DATE NOT NULL,
   RE_NUM NUMBER NOT NULL,
    USER_ID VARCHAR2(50) NOT NULL,
   GUEST VARCHAR2(100) NOT NULL,
    PAYMENT_STATUS CHAR(1) DEFAULT 'N',
      CONSTRAINT PK_RE_NO PRIMARY KEY (RE_NUM)
);

COMMENT ON COLUMN RESERVATION.ROOM_NO IS '숙소 번호';
COMMENT ON COLUMN RESERVATION.A_NUM IS '성인';
COMMENT ON COLUMN RESERVATION.C_NUM IS '어린이';
COMMENT ON COLUMN RESERVATION.I_NUM IS '유아';
COMMENT ON COLUMN RESERVATION.CHECKIN_DATE IS '체크인 날짜';
COMMENT ON COLUMN RESERVATION.CHECKOUT_DATE IS '체크아웃 날짜';
COMMENT ON COLUMN RESERVATION.RE_NUM IS '예약 번호';
COMMENT ON COLUMN RESERVATION.USER_ID IS '예약 아이디';
COMMENT ON COLUMN RESERVATION.GUEST IS '게스트';
COMMENT ON COLUMN RESERVATION.PAYMENT_STATUS IS '결제상태';

-- 숙소
DROP TABLE ROOM CASCADE CONSTRAINTS;
CREATE TABLE ROOM (
   ROOM_NO      NUMBER      NOT NULL,
   USER_ID      VARCHAR2(50)   NOT NULL,
   ROOM_NAME   VARCHAR2(100)   NOT NULL,
   ROOM_CONTENT   VARCHAR2(2000)      NOT NULL,
   ROOM_ADDRESS   VARCHAR2(100)   NOT NULL,
    ROOM_ROADADDRESS VARCHAR2(100) NOT NULL,
    ST_NUM_PEOPLE   NUMBER      NOT NULL,
   MAX_PEOPLE   NUMBER      NOT NULL,
   CHECKIN_TIME   VARCHAR2(50)   NOT NULL,
   CHECKOUT_TIME   VARCHAR2(50)   NOT NULL,
   BED      NUMBER      NOT NULL,
   BEDROOM   NUMBER      NOT NULL,
   BATHROOM   NUMBER      NOT NULL,
   AMENITY   VARCHAR2(2000),
   FACILITY   VARCHAR2(2000),
   BUILD_TYPE   VARCHAR2(2000),
   RULE   VARCHAR2(2000),
   PASS_OR_NOT   CHAR(1)      default 'N',   
   PLUS_CHARGE   NUMBER,
    ROOM_WEEKDAY NUMBER NOT NULL,
    ROOM_WEEKEND NUMBER NOT NULL,
     
    CONSTRAINT PK_RNO PRIMARY KEY (ROOM_NO)
);
COMMENT ON COLUMN ROOM.ROOM_NO IS '숙소번호';
COMMENT ON COLUMN ROOM.USER_ID IS '이메일아이디';
COMMENT ON COLUMN ROOM.ROOM_NAME IS '숙소이름';
COMMENT ON COLUMN ROOM.ROOM_CONTENT IS '숙소내용';
COMMENT ON COLUMN ROOM.ROOM_ADDRESS IS '숙소주소';
COMMENT ON COLUMN ROOM.ST_NUM_PEOPLE IS '기준인원';
COMMENT ON COLUMN ROOM.MAX_PEOPLE IS '최대인원';
COMMENT ON COLUMN ROOM.CHECKIN_TIME IS '체크인시간';
COMMENT ON COLUMN ROOM.CHECKOUT_TIME IS '체크아웃시간';
COMMENT ON COLUMN ROOM.BED IS '침대수';
COMMENT ON COLUMN ROOM.BEDROOM IS '침실수';
COMMENT ON COLUMN ROOM.BATHROOM IS '욕실수';
COMMENT ON COLUMN ROOM.AMENITY IS '편의시설';
COMMENT ON COLUMN ROOM.FACILITY IS '시설';
COMMENT ON COLUMN ROOM.BUILD_TYPE IS '건물유형';
COMMENT ON COLUMN ROOM.RULE IS '이용규칙';
COMMENT ON COLUMN ROOM.PASS_OR_NOT IS '통과여부';
COMMENT ON COLUMN ROOM.PLUS_CHARGE IS '추가인원 금액';
COMMENT ON COLUMN ROOM.ROOM_ROADADDRESS IS '도로명 주소';
COMMENT ON COLUMN ROOM.ROOM_WEEKDAY IS '평일 가격';
COMMENT ON COLUMN ROOM.ROOM_WEEKEND IS '주말 가격';

--숙소 위도 경도
DROP TABLE ROOM_LATLNG CASCADE CONSTRAINTS;
CREATE TABLE ROOM_LATLNG (
ROOM_NO NUMBER,
ROOM_LAT NUMBER,
ROOM_LNG NUMBER,
CONSTRAINT PK_LATLNG_RNO PRIMARY KEY (ROOM_NO)
);

COMMENT ON COLUMN ROOM_LATLNG.ROOM_NO IS '숙소 번호';
COMMENT ON COLUMN ROOM_LATLNG.ROOM_LAT IS '위도';
COMMENT ON COLUMN ROOM_LATLNG.ROOM_LNG IS '경도';


-- 숙소 사진
DROP TABLE ROOM_FILE CASCADE CONSTRAINTS;
CREATE TABLE ROOM_FILE (
   ROOM_FILE_NO    NUMBER,
    ROOM_NO      NUMBER      NOT NULL,
   ORIGINAL_FILE   VARCHAR2(50),
   RENAME_FILE   VARCHAR2(50),       
    CONSTRAINT PK_RFNO PRIMARY KEY (ROOM_FILE_NO)
);
COMMENT ON COLUMN ROOM_FILE.ROOM_FILE_NO IS '사진번호';
COMMENT ON COLUMN ROOM_FILE.ORIGINAL_FILE IS '숙소대표사진';
COMMENT ON COLUMN ROOM_FILE.RENAME_FILE IS '숙소바뀐사진';
COMMENT ON COLUMN ROOM_FILE.ROOM_NO IS '숙소번호';


-- 숙소 리뷰
DROP TABLE REVIEW CASCADE CONSTRAINTS;
CREATE TABLE REVIEW (
   REPLY_NO NUMBER,
   CLEAN_SCORE   NUMBER NOT NULL,
   VALUE_SCORE   NUMBER NOT NULL,
   SERVICE_SCORE   NUMBER NOT NULL,
   REVIEW_CONTENT   VARCHAR2(1000) NOT NULL,
   REVIEW_LEVEL   NUMBER DEFAULT 0,
   REVIEW_REF   NUMBER,
   REVIEW_SEQ   NUMBER,
   ROOM_NO   NUMBER NOT NULL,
   USER_ID   VARCHAR2(50) NOT NULL,
   REVIEW_DATE        DATE DEFAULT SYSDATE,
    CONSTRAINT PK_REP_NO PRIMARY KEY (REPLY_NO)
);

COMMENT ON COLUMN REVIEW.REPLY_NO IS '리뷰 번호';
COMMENT ON COLUMN REVIEW.CLEAN_SCORE IS '청결도 점수';
COMMENT ON COLUMN REVIEW.VALUE_SCORE IS '가격대비 만족도 점수';
COMMENT ON COLUMN REVIEW.SERVICE_SCORE IS '서비스 점수';
COMMENT ON COLUMN REVIEW.REVIEW_CONTENT IS '리뷰 내용';
COMMENT ON COLUMN REVIEW.REVIEW_LEVEL IS '리뷰 레벨';
COMMENT ON COLUMN REVIEW.REVIEW_REF IS '대댓글 번호';
COMMENT ON COLUMN REVIEW.REVIEW_SEQ IS '대댓글 순번';
COMMENT ON COLUMN REVIEW.ROOM_NO IS '숙소 번호';
COMMENT ON COLUMN REVIEW.USER_ID IS '회원 아이디';
COMMENT ON COLUMN REVIEW.REVIEW_DATE IS '리뷰 등록날짜';



-- 사용자 알림
DROP TABLE USER_NOTICE CASCADE CONSTRAINTS;
CREATE TABLE USER_NOTICE (
   NOTICE_NO   NUMBER NOT NULL,
   NOTICE_CONTENT   VARCHAR2(200) NOT NULL,
   NOTICE_DATE   DATE DEFAULT SYSDATE,
    READ_CHECK CHAR(1) DEFAULT 'N',
   TO_USER   VARCHAR2(50) NOT NULL,
    FROM_USER VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_USERNOTICE_NO PRIMARY KEY (NOTICE_NO)
);

COMMENT ON COLUMN USER_NOTICE.NOTICE_NO IS '알림 번호';
COMMENT ON COLUMN USER_NOTICE.NOTICE_CONTENT IS '알림 내용';
COMMENT ON COLUMN USER_NOTICE.NOTICE_DATE IS '알림 날짜';
COMMENT ON COLUMN USER_NOTICE.READ_CHECK IS '읽기 체크';
COMMENT ON COLUMN USER_NOTICE.TO_USER IS '받는 사람';
COMMENT ON COLUMN USER_NOTICE.FROM_USER IS '보낸 사람';


-- 알림 관리
DROP TABLE NOTICE CASCADE CONSTRAINTS;
CREATE TABLE NOTICE(
NOTICE_TYPE_NO NUMBER,
NOTICE_CONTENT1 VARCHAR2(200),
NOTICE_CONTENT2 VARCHAR2(200),

CONSTRAINT PK_NO_TYPE PRIMARY KEY (NOTICE_TYPE_NO)
);
COMMENT ON COLUMN NOTICE.NOTICE_TYPE_NO IS '알림 유형';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT1 IS '알림 내용1';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT2 IS '알림 내용2';


-- FOREIGN KEY
-- 내가 저장한 숙소
ALTER TABLE MY_ROOM
ADD CONSTRAINT FK_MR_UID FOREIGN KEY (USER_ID) REFERENCES MEMBER ON DELETE CASCADE;
ALTER TABLE MY_ROOM
ADD CONSTRAINT FK_MR_RN FOREIGN KEY (ROOM_NO) REFERENCES ROOM ON DELETE CASCADE;

--내가 저장한 쿠폰
ALTER TABLE MY_COUPON
ADD CONSTRAINT FK_MCP_UID FOREIGN KEY (USER_ID) REFERENCES MEMBER ON DELETE CASCADE;
ALTER TABLE MY_COUPON
ADD CONSTRAINT FK_MCP_CPN FOREIGN KEY (COUPON_NO) REFERENCES COUPON ON DELETE CASCADE;

-- 예약내역
ALTER TABLE RESERVATION
ADD CONSTRAINT FK_RE_UID FOREIGN KEY (USER_ID) REFERENCES MEMBER ON DELETE CASCADE;

-- 관광지
ALTER TABLE TOUR
ADD CONSTRAINT FK_TOUR_UID FOREIGN KEY (USER_ID) REFERENCES MEMBER ON DELETE CASCADE;
ALTER TABLE TOUR
ADD CONSTRAINT FK_TOUR_CAT FOREIGN KEY (TOUR_CATEGORY_NO) REFERENCES TOUR_CATEGORY ON DELETE CASCADE;

-- 관광지 사진
ALTER TABLE TOUR_IMAGE
ADD CONSTRAINT FK_TOUR_IMG FOREIGN KEY (TOUR_NO) REFERENCES TOUR ON DELETE CASCADE;

-- 관광지 좋아요
ALTER TABLE TOUR_LIKE
ADD CONSTRAINT FK_TOUR_LIKE FOREIGN KEY (TOUR_NO) REFERENCES TOUR ON DELETE CASCADE;
ALTER TABLE TOUR_LIKE
ADD CONSTRAINT FK_TOUR_LID FOREIGN KEY (USER_ID) REFERENCES MEMBER ON DELETE CASCADE;

-- 관광지 리뷰
ALTER TABLE TOUR_REVIEW
ADD CONSTRAINT FK_TOUR_REV FOREIGN KEY (TOUR_NO) REFERENCES TOUR ON DELETE CASCADE;
ALTER TABLE TOUR_REVIEW
ADD CONSTRAINT FK_TOUR_RID FOREIGN KEY (USER_ID) REFERENCES MEMBER ON DELETE CASCADE;

-- 슥소 사진
ALTER TABLE ROOM_FILE
ADD CONSTRAINT FK_RNOO_RF FOREIGN KEY (ROOM_NO) REFERENCES ROOM;

--숙소 위도 경도
ALTER TABLE ROOM_LATLNG
ADD CONSTRAINT FK_LATLNG_RNO FOREIGN KEY (ROOM_NO) REFERENCES ROOM;

-- 알림
ALTER TABLE USER_NOTICE
ADD CONSTRAINT FK_TO_UID FOREIGN KEY (TO_USER) REFERENCES MEMBER;
ALTER TABLE USER_NOTICE
ADD CONSTRAINT FK_FROM_UID FOREIGN KEY (FROM_USER) REFERENCES MEMBER;


-- 숙소 리뷰
ALTER TABLE REVIEW
ADD CONSTRAINT FK_RV_RNO FOREIGN KEY (ROOM_NO) REFERENCES ROOM;
ALTER TABLE REVIEW
ADD CONSTRAINT KF_RV_UID FOREIGN KEY (USER_ID) REFERENCES MEMBER;

-- 이벤트
ALTER TABLE EVENT
ADD CONSTRAINT FK_EVENT_COP FOREIGN KEY (COUPON_NO) REFERENCES COUPON ON DELETE CASCADE;

-- 1대1 문의
ALTER TABLE QUESTION
ADD CONSTRAINT FK_QUESTION_UID FOREIGN KEY (USER_ID) REFERENCES MEMBER ON DELETE CASCADE;
ALTER TABLE QUESTION
ADD CONSTRAINT FK_QUESTION_QTYPENO FOREIGN KEY (QUESTIONTYPE_NO) REFERENCES QUESTION_TYPE ON DELETE CASCADE;

-- 자주묻는 질문
ALTER TABLE FAQ
ADD CONSTRAINT FK_FAQ_FTYPENO FOREIGN KEY (FAQCATEGORY_NO) REFERENCES FAQ_TYPE ON DELETE CASCADE;

COMMIT;